services:
  - type: web
    name: khana-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true
    rootDir: backend
    envVars:
      - key: MONGO_URI
        value: your-mongodb-connection-string
      - key: JWT_SECRET
        value: your-secret-key
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: khana-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    plan: free
    autoDeploy: true
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://khana-backend.onrender.com
